### ISSUE TITLE
The Readme Updates

### ISSUE THREAD

**Issue by Pragya2056** [mubashir72/Hacktoberfest_2022#4]
The Readme could be more updated with the mention of: -

1. What is hacktoberfest?
2. What is the repo requirements?
3. How to contribute?
4. The rules
5. The Code of Conduct
6. Contributors mention

**Comment by Pragya2056** [comment]
Please assign me in the issue and I will prepare a documentation on this.

**Comment by mubashir72** [comment]
assigned to pargya2056

**Comment by Pragya2056** [comment]
#8 
The issue is looked at.

**Comment by Pragya2056** [comment]
@mubashir72 
Please review the PR.

**Comment by Pragya2056** [comment]
Thank you
