### ISSUE TITLE
The more clear CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Pragya2056** [mubashir72/Hacktoberfest_2022#5]
The CONTRIBUTING.md file is not as clear as it should be.

**Comment by Pragya2056** [comment]
Please assign me and I will prepare a clear document on the CONTRIBUTING.md file.

**Comment by mubashir72** [comment]
assigned to pragya2056

**Comment by Pragya2056** [comment]
The issue was looked at #7

**Comment by Pragya2056** [comment]
Thank you!!!
